#docker-compose
version: "3.9"

services:
  backend:
    container_name: 'botkit-backend'
    build:
      context: .
    ports:
      - "${PORT_CONTAINER:-3000}:${APP_PORT:-3000}"
    env_file:
      - .env
    restart: always
    networks:
      - back
      - default

  mongo:
    container_name: 'botkit-mongodb'
    image: mongo:latest
    restart: always
    env_file:
      - .env
    ports:
      - "27017:${MONGO_PORT:-27017}"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    networks:
      - back
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: mongosh --eval "rs.initiate()"
      start_period: 5s

networks:
  back:
    driver: bridge
    internal: true

volumes:
  db_data:
  db_config:
